services:
  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - 8010:8080
    command:
      - start-dev
    networks:
      - keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  keycloak:
    driver: bridge