  

services:  
  mongo:  
    image: mongo:8.0.4
    container_name: mongo  
    ports:  
      - "27017:27017"  
    volumes:  
      - ./data:/data/db  
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: always  

volumes:  
  mongo-data: